// ALl of the systems frontend data will comes here

export let feedData = [
	//******************************************************************** */
	{
		keyId: '1',
		subjectName: 'Capstone',
		quizDetails: {
			chapter: 1,
			instruction:
				'MULTIPLE CHOICE. Read and understand the statement carefully and choose the letter of the correct answer.',
			title: 'Basic knowledge in researching',
			quizLengthTime: 5,
		},
		subjectLink: '../subjects page/subject_page.html',
		quizLink: '../quiz page/quiz_page.html',
		quizLinkAtHomePage: './quiz page/quiz_page.html',
		module: './modules/CAPSTONE_MODULE.pdf',
		outsideFileModule: '../modules/CAPSTONE_MODULE.pdf',
		questions: [
			{
				questionNum: 1,
				question:
					'An article is a piece of writing written for a large audience. The main motive behind writing an article is that it should be published in either newspapers or magazines or journals so as to make some difference to the world.',
				a: 'Article Writing',
				b: 'Articles',
				c: 'The Format of Article Writing',
				d: 'Target Audience',
				correct: 'a',
			},
			{
				questionNum: 2,
				question: 'Identify the concerning reading group.',
				a: 'Collect & Select',
				b: 'Purpose',
				c: 'Target Audience',
				d: 'Organize',
				correct: 'c',
			},
			{
				questionNum: 3,
				question: 'Arrange the information and the facts in a logical way',
				a: 'Organize',
				b: 'Purpose',
				c: 'Target Audience',
				d: 'Collect & Select ',
				correct: 'a',
			},
			{
				questionNum: 4,
				question:
					'Gather as such information as possible. Also, identify the details that are most significant',
				a: 'Collect & Select',
				b: 'Purpose',
				c: 'Target Audience',
				d: 'Organize',
				correct: 'a',
			},
			{
				questionNum: 5,
				question: 'Find the objective or aim of writing the article',
				a: 'Purpose',
				b: 'Target Audience',
				c: 'Collect & Select',
				d: 'Organize',
				correct: 'a',
			},
			{
				questionNum: 6,
				question: 'Common Mistakes in the Article Writing Format',
				a: 'Use vocabulary skill',
				b: 'Keep the introduction of the topic catching, interesting, and short',
				c: 'Discuss the opinion and the matter in an organized and descriptive manner',
				d: 'Not using facts or quotes or similar cases',
				correct: 'd',
			},
			{
				questionNum: 7,
				question: 'Steps for Article Writing Format',
				a: 'The language should not be too formal',
				b: 'No use of paragraphs expressing personal views is fine but the author must never talk about himself/herself',
				c: 'The article must be in easy language for better understanding',
				d: 'Use vocabulary skill',
				correct: 'd',
			},
			{
				questionNum: 8,
				question: 'Common Mistakes in the Article Writing Format',
				a: 'Use vocabulary skill',
				b: 'The title of the article must be catchy and clearly understandable',
				c: 'Keep the introduction of the topic catching, interesting, and short',
				d: 'Discuss the opinion and the matter in an organized and descriptive manner',
				correct: 'b',
			},
			{
				questionNum: 9,
				question: 'Common Mistakes in the Article Writing Format',
				a: 'Use vocabulary skill',
				b: 'Keep the introduction of the topic catching, interesting, and short',
				c: 'The article must be in easy language for better understanding',
				d: 'Discuss the opinion and the matter in an organized and descriptive manner',
				correct: 'c',
			},
			{
				questionNum: 10,
				question: 'Points to keep in mind for the Article Writing Format',
				a: 'It has to be interesting',
				b: 'The language should not be too formal',
				c: 'The article must be in easy language for better understanding',
				d: 'The title of the article must be catchy and clearly understandable',
				correct: 'a',
			},
		],
	},
	{
		keyId: '2',
		subjectName: 'STATS',
		quizDetails: {
			chapter: 1,
			instruction:
				'MULTIPLE CHOICE. Read and understand the statement carefully and choose the letter of the correct answer.',
			title: 'Basic computing',
			quizLengthTime: 5,
		},
		subjectLink: '../subjects page/subject_page.html',
		quizLink: '../quiz page/quiz_page.html',
		quizLinkAtHomePage: './quiz page/quiz_page.html',
		module: './modules/STATS_MODULE.pdf',
		outsideFileModule: '../modules/STATS_MODULE.pdf',
		questions: [
			{
				questionNum: 1,
				question:
					'Collection of all outcomes, responses, measurements, or counts that are of interest.',
				a: 'Population',
				b: 'Sample',
				c: 'Experiment',
				d: 'Elementary unit or Element',
				correct: 'a',
			},
			{
				questionNum: 2,
				question: 'Is a subset, or part, of a population. ',
				a: 'Experiment',
				b: 'Elementary unit or Element',
				c: 'Population',
				d: 'Sample',
				correct: 'd',
			},
			{
				questionNum: 3,
				question:
					'It is a member of the population whose measurement on the variable of interest is what we wish to examine.',
				a: 'Experiment',
				b: 'Population',
				c: 'Sample',
				d: 'Elementary unit or Element',
				correct: 'd',
			},
			{
				questionNum: 4,
				question: 'A planned activity whose results yield a set of data.',
				a: 'Experiment',
				b: 'Population',
				c: 'Sample',
				d: 'Elementary unit or Element',
				correct: 'a',
			},
			{
				questionNum: 5,
				question:
					'Are variables controlled by the experimenter/researcher, andexpected to have an effect on the behavior of the subjects. The independent variable is also called explanatory variable.',
				a: 'Independent variables',
				b: 'Dependent variable',
				c: 'Parameter',
				d: 'Statistic',
				correct: 'a',
			},
			{
				questionNum: 6,
				question:
					'Is some measure of the behavior of subjects and expected to be influenced by the independent variable. The dependent variable is also called outcome variable.',
				a: 'Independent variables',
				b: 'Dependent variable',
				c: 'Parameter',
				d: 'Statistic',
				correct: 'b',
			},
			{
				questionNum: 7,
				question: 'A numerical description of a population characteristic.',
				a: 'Independent variables',
				b: 'Dependent variable',
				c: 'Parameter',
				d: 'Statistic',
				correct: 'c',
			},
			{
				questionNum: 8,
				question: 'A numerical description of a sample characteristic.',
				a: 'Independent variables',
				b: 'Dependent variable',
				c: 'Parameter',
				d: 'Statistic',
				correct: 'd',
			},
			{
				questionNum: 9,
				question:
					'Are date documented by the primary source. The data collectors themselves documented this data.',
				a: 'Primary data',
				b: 'Surveys',
				c: 'Secondary data',
				d: 'Personal Interview',
				correct: 'a',
			},
			{
				questionNum: 10,
				question:
					'It is a method of collecting data on the variable of interest by asking people questions. When data came from asking all the people in the population, then the study is called a census*. On the other hand, when data came from asking a sample of people selected from a well-defined population, then the study is called sample survey.',
				a: 'Primary data',
				b: 'Surveys',
				c: 'Secondary data',
				d: 'Personal Interview',
				correct: 'b',
			},
		],
	},
	{
		keyId: '3',
		subjectName: 'CC05',
		quizDetails: {
			chapter: 1,
			instruction:
				'MULTIPLE CHOICE. Read and understand the statement carefully and choose the letter of the correct answer.',
			title: 'Please answer',
			quizLengthTime: 5,
		},
		subjectLink: '../subjects page/subject_page.html',
		quizLink: '../quiz page/quiz_page.html',
		quizLinkAtHomePage: './quiz page/quiz_page.html',
		// module: './modules/CC05_MODULE.pdf',
		module:
			'https://e.edim.co/207860524/DpqJap4LVTjLiqTv.pdf?response-content-disposition=filename%3D%22CCO5__CHAPTER1.pdf%22%3B%20filename%2A%3DUTF-8%27%27CCO5-%2520CHAPTER1.pdf&Expires=1656679452&Signature=V64UZ8KlU~ly4ZCyCR1hC~e6KZnEnzqJmhAdXmPaORz7XLqUc03cYHm-DvJoTNBwUPA8j1DmWNoZt~JdrPZ8J-0OiN-F23bYG8BVWilMgtUrHtIS60wmljZy2uyYWDLPY8VuchJR6j8Fb9VddnB6JnkkL8qFAAVfwBC-f~urkLDswyLgpieRXCjjIFGyYInVmihN10SDelQWJTsy2gbvzfLcQ~8Y2rk0y00~~7SRFi3ExfEQI9lXAUDSQbdW2xJUfhxdtr0zxz83yYzyV4jw2BZ9ZtFWeTvrNWMKmE-xCY6qFcpZwWPGxLci1q-gb8MUVn1XoT6ip9w3ke7E9~zeCg__&Key-Pair-Id=APKAJMSU6JYPN6FG5PBQ',
		outsideFileModule: '../modules/CC05_MODULE.pdf',
		questions: [
			{
				questionNum: 1,
				question:
					'Is mass- produced, copyrighted retail software that meets the needs of a wide variety of users, not just a single user or company. Packaged software is available in retail stores or on the WEB.',
				a: 'PACKAGED SOFTWARE',
				b: 'CUSTOM SOFTWARE',
				c: 'WEB APPLICATION',
				d: 'OPEN SOURCE SOFTWARE',
				correct: 'a',
			},
			{
				questionNum: 2,
				question:
					'Performs functions specific to a business or industry. Sometimes a company cannot find packaged software that meets its unique requirements.',
				a: 'PACKAGED SOFTWARE',
				b: 'CUSTOM SOFTWARE',
				c: 'WEB APPLICATION',
				d: 'OPEN SOURCE SOFTWARE',
				correct: 'b',
			},
			{
				questionNum: 3,
				question:
					'Is a Website that allows users to access and interact with software from any computer or device that is connected to the Internet. Many Web sites provide free access to their programs; some charge a fee.',
				a: 'PACKAGED SOFTWARE',
				b: 'CUSTOM SOFTWARE',
				c: 'WEB APPLICATION',
				d: 'OPEN SOURCE SOFTWARE',
				correct: 'c',
			},
			{
				questionNum: 4,
				question:
					'Is a software provided fir use, modification, and redistribution. This software has no restrictions from the copyright holder regarding modification of the software’s internal instructions and it’s redistribution.',
				a: 'PACKAGED SOFTWARE',
				b: 'CUSTOM SOFTWARE',
				c: 'WEB APPLICATION',
				d: 'OPEN SOURCE SOFTWARE',
				correct: 'd',
			},
			{
				questionNum: 5,
				question:
					'That is distributed at no cost for a trial period. To use a shareware program beyond that period, you send payment to the program developer.',
				a: 'SHAREWARE IS COPYRIGHTED SOFTWARE',
				b: 'FREEWARE IS COPYRIGHTED SOFTWARE',
				c: 'PUBLIC DOMAIN SOFTWARE',
				d: 'OPEN SOURCE SOFTWARE',
				correct: 'a',
			},
			{
				questionNum: 6,
				question:
					'Provided at no cost by an individual or a company that retains all rights to the software.',
				a: 'SHAREWARE IS COPYRIGHTED SOFTWARE',
				b: 'FREEWARE IS COPYRIGHTED SOFTWARE',
				c: 'PUBLIC DOMAIN SOFTWARE',
				d: 'OPEN SOURCE SOFTWARE',
				correct: 'b',
			},
			{
				questionNum: 7,
				question:
					'Has been donated for public use and has no copyright restrictions. Anyone can copy or distribute public-domain software to others at no cost.',
				a: 'SHAREWARE IS COPYRIGHTED SOFTWARE',
				b: 'FREEWARE IS COPYRIGHTED SOFTWARE',
				c: 'PUBLIC DOMAIN SOFTWARE',
				d: 'OPEN SOURCE SOFTWARE',
				correct: 'c',
			},
			{
				questionNum: 8,
				question:
					'Elements visible on each of the screen of the mobile application are discussed and noted down as wireframes.',
				a: 'PROCESS FLOW',
				b: 'WIRE FRAME',
				c: 'STORYBOARD',
				d: 'ARCHITECTURE DESIGN',
				correct: 'b',
			},
			{
				questionNum: 9,
				question:
					'Everything including the images to be shown, icons appearing, theme, color, background, etc is a part of storyboard.',
				a: 'PROCESS FLOW',
				b: 'WIRE FRAME',
				c: 'STORYBOARD',
				d: 'ARCHITECTURE DESIGN',
				correct: 'c',
			},
			{
				questionNum: 10,
				question:
					'Planning and development of application architecture is performed. Coding is done to give life to the application',
				a: 'PROCESS FLOW',
				b: 'WIRE FRAME',
				c: 'STORYBOARD',
				d: 'ARCHITECTURE DESIGN',
				correct: 'd',
			},
		],
	},
];
